spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/<DATABASE_NAME> # Defined in db\secrets.env (POSTGRES_DB)
    driver-class-name: org.postgresql.Driver
    username: <CHANGE_ME> # POSTGRES_USER
    password: <CHANGE_ME> # POSTGRES_PASSWORD
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

corsserver: http://<YOUR_DOMAIN>:<YOUR_PORT>/ # For frontend 
