
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost}:5432/${POSTGRES_DB:commean_dev}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:user} # Enviromental variable or custom URL
    password: ${POSTGRES_PASSWORD:password} # Enviromental variable or custom URL
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  thymeleaf:
    prefix: classpath:/templates/
commean:
  cross-server: http://${FRONTEND_URL:localhost}:8081/
  jwt-secret: ${JWT_SECRET:M2QjcWdpb1VlMkBkTlMjR1RkaSZmY2k2Q3ZKd0pzI15ERmhpNzVYaFVANDY3NyNrZlohbk1SclRwUkZBQyReNVV1VzZAOWVwYSZObTRMRUNIOFQ2b29vNFBYSjk5dHhkR2olODZRRTZLMiFKcmg4YlpEJSY1QXQlJkBkKjJEXkg=}
  jwt-exp: ${JWT_TTL:180}
  mqtt:
    ttn-app-id: ${TTN_APP_ID:commean}
    ttn-url: ${TTN_URL:ssl://eu1.cloud.thethings.network:8883}
    ttn-api-key: ${TTN_APIKEY:NNSXS.5KJPA4ZPKBXVQPCMSZJL4MCV5U4ICSUPFOOTJLI.AWXQJQF6PIF5BMHQOWVWHBRCQRTGH6JKD2CB2QM42M4IUIOLKN6A}
    client-id: ${CLIENT_ID:test}
logging:
  level:
    eu.commean.backend: DEBUG
server:
  error:
    include-stacktrace: on_param
springdoc:
  swagger-ui:
    path: /
