spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/commean_dev
    driver-class-name: org.postgresql.Driver
    username: <CHANGE_ME>
    password: <CHANGE_ME>
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

corsserver: http://<YOUR_DOMAIN>:<YOUR_PORT>/ # For frontend 
