version: "3.8"

services:
  
  timescaledb:
    image : "timescale/timescaledb:latest-pg12"
    ports:
      - 5432:5432
    env_file:
      - secrets.env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
